#GPIO mapping of all the different input and output sensors and switches

GARAGE_OPENER = 2
GARAGE_SENSOR_UP = 17
GARAGE_SENSOR_DOWN = 27

CHRISTMAS_LIGHTS_ZONE_ONE = 4
#CHRISTMAS_LIGHTS_ZONE_TWO = 0
#CHRISTMAS_LIGHTS_ZONE_THREE = 0

GARAGE_LIGHTS_ZONE_ONE = 3
GARAGE_LIGHTS_ZONE_TWO = 5

#OUTSIDE_LIGHTS_ZONE_ONE = 0
#OUTSIDE_LIGHTS_ZONE_TWO = 0

#SPRINKLER_ZONE_ONE = 0
#SPRINKLER_ZONE_TWO = 0
#SPRINKLER_ZONE_THREE = 0
#SPRINKLER_ZONE_FOUR = 0
