#GPIO mapping of all the different input and output sensors and switches

GARAGE_OPENER = 2
GARGER_SENSOR_UP = 0
GARGER_SENSOR_DOWN = 0

CHRISTMAS_LIGHTS_ZONE_ONE = 0
CHRISTMAS_LIGHTS_ZONE_TWO = 0
CHRISTMAS_LIGHTS_ZONE_THREE = 0

SPRINKLER_ZONE_ONE = 0
SPRINKLER_ZONE_TWO = 0
SPRINKLER_ZONE_THREE = 0
SPRINKLER_ZONE_FOUR = 0
